name: Bug report
description: Report an issue or bug with this Advanced HTML Snippets extension
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: non_api
    attributes:
      label: Confirm this is a Advanced HTML Snippets extension issue and not an underlying issue
      description: Issues with the underlying should be reported on our [Developer Community](https://support.codegyan.in)
      options:
        - label: This is an issue with the Advanced HTML Snippets extension
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is, and any additional context.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: code-snippets
    attributes:
      label: Code snippets
      description: If applicable, add code snippets to help explain your problem.
      render: JavaScript
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: macOS
    validations:
      required: true